# Numpy

# An Example of Calculation using List

In [10]:
#list
height=[1.73,1.68,1.71]



weight=[65.4,59.2,88.1]

print(height)
print(weight)
print('**************')

#type(height)

#bmi=weight/height*2

for h in height:
    for  w in weight:
        b=w/h*2
    print (b)
    
#print(bmi)

[1.73, 1.68, 1.71]
[65.4, 59.2, 88.1]
**************
101.84971098265895
104.88095238095238
103.04093567251462


# How Numpy is better than List

# An Example of Calculation using Numpy

In [24]:
import numpy as np
import numpy as pat1



#list
height=[1.73,1.68,1.71]

weight=[65.4,59.2,88.1]

#we are creating a numpy array from a List
np_height = np.array(height)
np_weight = np.array(weight)

np_height.

print(np_height)
bmi = np_weight/np_height*2
print(bmi)

[1.73 1.68 1.71]
[ 75.60693642  70.47619048 103.04093567]


# 1- Dimension Numpy Array

In [30]:
a = np.array([1,2,3,4,5,6,7])
print('*****')
print(a)
print('*****')
print(type(a))
print('*****')
print(a.ndim)
print('*****')

print(a.shape)
print('*****')



*****
[1 2 3 4 5 6 7]
*****
<class 'numpy.ndarray'>
*****
1
*****
(7,)
*****


In [22]:
[1,2,3,4,5,6,7]

[1, 2, 3, 4, 5, 6, 7]

In [25]:
np1 = pat1.array([1,2,3,4,5,6,7])

In [26]:
np1

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
print(np1)

[1 2 3 4 5 6 7]


# 2- Dimension Numpy Array

In [31]:

twoa = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print('*****')
print(twoa)
print('*****')
print(type(twoa))
print('*****')
print(twoa.ndim)
print('*****')
print(twoa.shape)

*****
[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]
*****
<class 'numpy.ndarray'>
*****
2
*****
(2, 7)


# 3- Dimension Numpy Array

In [32]:
threea = np.array([[[1,2,3,4,5,6,7]],[[1,2,3,4,5,6,7]],[[1,2,3,4,5,6,7]]])
print('*****')
print(threea)
print('*****')
print(type(threea))
print('*****')
print(threea.ndim)
print('*****')
print(threea.shape)

*****
[[[1 2 3 4 5 6 7]]

 [[1 2 3 4 5 6 7]]

 [[1 2 3 4 5 6 7]]]
*****
<class 'numpy.ndarray'>
*****
3
*****
(3, 1, 7)


# Initialize all the elements of x X y array to 0

In [35]:
c =np.zeros((5,5))

In [36]:
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
np.zeros((5,5),dtype = int)
#eek.zeros(2, dtype = int) 

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
np.ones((5,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [41]:
np.arange(1,10,3)

array([1, 4, 7])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#np.linspace(5-start,10-end,4-digits in between 5 and 10)
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])