# Numpy Assignment

In [1]:
import numpy as np

1.) Initialize a numpy array of 5*5 dimensions with all the values to be 0

In [2]:
znp = np.zeros([5,5])
print(znp)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2.) Create a numpy array with initial value 10 and final 100 with an interval of 5 between each value

In [3]:
a = np.arange(10,100,5)
print(a)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


3.) Create a 2-D array with values(10,20,30,40,50,60) and set the dimension to be 2*3.
        a. Print the number of elements in the array
        b. Get the data-type of the array

In [4]:
b = np.array([10,20,30,40,50,60]).reshape(2,3)
print('No. of elements:',b.size)
print('Data type of array:',b.dtype)

No. of elements: 6
Data type of array: int32


4.) Create first numpy array with values(1,2,3) and second with values(4,5,6).
Perform simple arithmetic operations on these two numpy arrays:
        a. Addition
        b. Subtraction
        c. Multiplication
        d. Division

In [5]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print('Addition :',x+y)
print('Subtraction :',x-y)
print('Multiplication :',x*y)
print('Division :',x/y)

Addition : [5 7 9]
Subtraction : [-3 -3 -3]
Multiplication : [ 4 10 18]
Division : [ 0.25  0.4   0.5 ]


5.) Create a numpy array with values 10-90 and set the shape to be 3*3.
        a. Extract only the 3rd column from the numpy array
        b. Extract only the 2nd row from the numpy array
        c. Extract those cells at the intersection of first two rows and first two columns

In [6]:
c = np.arange(10,91,10).reshape(3,3)
print('Numpy Array :\n',c)
print('\na.:\n',c[:,2])
print('\nb.:\n',c[1,:])
print('\nc.:\n',c[:2,:2])

Numpy Array :
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

a.:
 [30 60 90]

b.:
 [40 50 60]

c.:
 [[10 20]
 [40 50]]
