In [1]:
import numpy as np

#Create a Python numpy array

In [2]:
a1 = np.arange(1, 13)  # numbers 1 to 12
print(a1.shape)
print(a1)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


#Reshape with reshape() method

In [3]:
a1_2d = a1.reshape(3, 4)  # 3_4

print(a1_2d.shape)

print(a1_2d)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
a1.reshape(3, 4)
a1.reshape(-1, 4)  # same as above: a1.reshape(3, 4)

a1.reshape(3, 4)
a1.reshape(3, -1)  # same as above: a1.reshape(3, 4)

a1.reshape(2, 6)
a1.reshape(2, -1)  # same as above: a1.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#Reshape along different dimensions

In [5]:
a1.reshape(3, 4) # reshapes or ‘fills in’ row by row
a1.reshape(3, 4, order='C') # same results as above

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a1.reshape(3, 4, order='F')  # reshapes column by column

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [7]:
print(a1)  # what's the shape?

print(a1.shape)

a1_1_by_12 = a1.reshape(1, -1)  # reshape to 1_12

print(a1_1_by_12)  # note the double square brackets!

print(a1_1_by_12.shape)  # 1_12 array

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)


#Flatten/ravel to 1D arrays with ravel()

In [8]:
print(a1_2d)  # 3_4

print(a1_2d.ravel())  # ravel by row (default order='C')

print(a1_2d.ravel(order='F'))  # ravel by column

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  5  9  2  6 10  3  7 11  4  8 12]


#Concatenate/stack arrays with np.stack() and np.hstack()

In [9]:
a1 = np.arange(1, 13)
print(a1)
a2 = np.arange(13, 25)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[13 14 15 16 17 18 19 20 21 22 23 24]


In [10]:
stack0 = np.stack((a1, a1, a2, a2))  # default stack along 0th axis
print(stack0.shape)

(4, 12)


In [11]:
stack1 = np.stack((a1, a1, a2, a2), axis=1)
print(stack1.shape)

print(stack1)

(12, 4)
[[ 1  1 13 13]
 [ 2  2 14 14]
 [ 3  3 15 15]
 [ 4  4 16 16]
 [ 5  5 17 17]
 [ 6  6 18 18]
 [ 7  7 19 19]
 [ 8  8 20 20]
 [ 9  9 21 21]
 [10 10 22 22]
 [11 11 23 23]
 [12 12 24 24]]


In [12]:
stack_long = np.hstack((a1, a2))
print(stack_long.shape)

(24,)


In [13]:
print(stack_long)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


#Create multi-dimensional array (3D)

In [14]:
a1 = np.arange(1, 13).reshape(3, -1)  # 3_4
a2 = np.arange(13, 25).reshape(3, -1)  # 3_4

print(a1)

print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


#Create a 3D array by stacking the arrays along different axes/dimensions

In [15]:
a3_0 = np.stack((a1, a2))  # default axis=0 (dimension 0)
a3_1 = np.stack((a1, a2), axis=1)  # along dimension 1
a3_2 = np.stack((a1, a2), axis=2)  # along dimension 2

print(a3_0.shape)

print(a3_1.shape)

print(a3_2.shape)

(2, 3, 4)
(3, 2, 4)
(3, 4, 2)


In [16]:
print(a3_0)

print(a3_1)

print(a3_2)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]
[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]


In [17]:
print(a1)  # check what's a1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# solutions
a3_0[0, :, :]
a3_0[0]  # same as above
a3_1[:, 0, :]
a3_2[:, :, 0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#Flatten multidimensional arrays

In [19]:
print(a3_0)

print(a3_0.ravel())

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


#Ravel column by column (order='F') to 1D arra

In [20]:
#Ravel column by column (order='F') to 1D arra
print(a3_0.ravel(order='F'))

[ 1 13  5 17  9 21  2 14  6 18 10 22  3 15  7 19 11 23  4 16  8 20 12 24]


#Reshape multidimensional arrays

In [21]:
# reshape row by row (default order=C) to 2D array
print(a3_0)  # 2_3_4
print(a3_0.reshape(4, -1))  # reshape to 4_6 (row by row)
print(a3_0.reshape(4, -1, order='F'))  # reshape (column by column)
print(a3_0.reshape(4, 2, 3))  # reshape to 4_2_3 (row by row)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 1  9  6  3 11  8]
 [13 21 18 15 23 20]
 [ 5  2 10  7  4 12]
 [17 14 22 19 16 24]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
