# PythonNumpyHands-On

List from Python

In [9]:
height=[1.73,1.68,1.71]

weight=[65.4,59.2,88.1]

print(height)
print(weight)

bmi=weight/height*2

[1.73, 1.68, 1.71]
[65.4, 59.2, 88.1]


TypeError: unsupported operand type(s) for /: 'list' and 'list'

# Create Numpy Array

In [10]:
import numpy as np

lheight=[1.73,1.68,1.71]

lweight=[65.4,59.2,88.1]

np_height= np.array(lheight)
#print(np_height)
np_weight= np.array(lweight)

print(np_height)

print(np_weight)

bmi=np_weight/np_height*2

print(bmi)

#np_height*2

[ 1.73  1.68  1.71]
[ 65.4  59.2  88.1]
[  75.60693642   70.47619048  103.04093567]


In [11]:
[1 2 3], [4 5 6]

SyntaxError: invalid syntax (<ipython-input-11-99bba03764a9>, line 1)

# 1-Dimensional Array

In [12]:
import numpy as np
#import numpy to make use of it in the program
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5 6 7 8]
1
(8,)


# 2-Dimensional Array

In [13]:
#import numpy as np
b = np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]]
2


# Intialize Numpy Array

# Initialize all the elements of x X y array to 0

In [14]:
#import numpy as np
np.zeros((5,5))
#np.
#lweight.

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
#set a datype as integer
np.zeros((3,4),dtype = int)
#eek.zeros(2, dtype = int) 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Arrange the numbers between x and y with an interval of z

In [16]:
#import numpy as np
#the last number 10 is not printed
np.arange(1,10,1)



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#import numpy as np
#the last number 10 is not printed
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# Arrange 'z' numbers between x and y

linspace-linear Space - linear equation

In [18]:
np.linspace(5,10,4)

array([  5.        ,   6.66666667,   8.33333333,  10.        ])

In [19]:
np.linspace(5,10,5)

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ])

In [20]:
np.linspace(0,10,6)

array([  0.,   2.,   4.,   6.,   8.,  10.])

Here the even space is .5

In [21]:
#what is linspace???
#How to use it
np.linspace(5,10,10)

array([  5.        ,   5.55555556,   6.11111111,   6.66666667,
         7.22222222,   7.77777778,   8.33333333,   8.88888889,
         9.44444444,  10.        ])

In [22]:
#even numbers between 0 to 10
np.linspace(0,10,6)

array([  0.,   2.,   4.,   6.,   8.,  10.])

# Filling SAME number in an array of dimension x X y

In [23]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

# Filling RANDOM number in an array of dimension x X y

In [24]:
np.random.random((2,3))



array([[ 0.81868884,  0.2853951 ,  0.81630493],
       [ 0.48520004,  0.55270277,  0.50528542]])

# Inspecting the array: Checking the Shape of the array

Retunns a tuple consisting of array Dimensions. Can also be used to Resize the Array

In [35]:
a = np.array([[2,3,4],[4,4,6]])
print(a.shape)

print(a)


(2, 3)
[[2 3 4]
 [4 4 6]]


In [26]:
s = np.array([[1,2,3,4],[2,3,4,6],[6,7,8,9]])
print(s.shape)

(3, 4)


# Shape: Inspecting the array and  Resize the Array

Shape function is either used to get the shape of already existing array by using arry_name.shape method.<br>Resize:Another way to use shape is to change array dimensions of the array. But note that shape changes dimensions of the original array



In [37]:
a = np.array([[2,3,4],[4,4,6]])
#print(a)
#print(a.shape)

a.shape = (3,2)
print(a)
print(a.shape)

a.shape = (2,3)
print(a)
print(a.shape)

#b = np.array([[10,11,12],[13,14,15]])
#b.shape = (3,2)
#print(b)             

[[2 3]
 [4 4]
 [4 6]]
(3, 2)
[[2 3 4]
 [4 4 6]]
(2, 3)


ndim:Return the dimension of the array

In [38]:
a = np.array([[2,3,4,4],[2,4,4,6]])
print(a)
print(a.ndim)
print(a.shape)
print('*******')
a.shape = (8,1) #Trick: x*y = Total number of elements in the array
print(a)
print(a.ndim)
print(a.shape)

[[2 3 4 4]
 [2 4 4 6]]
2
(2, 4)
*******
[[2]
 [3]
 [4]
 [4]
 [2]
 [4]
 [4]
 [6]]
2
(8, 1)


# Reshape

Reshape also changes the dimension of the array but it generates a new copy of the array in the process. So the original array remains unchanged.

In [8]:
import numpy as np
a = np.arange(24)
b = np.arange(24)
print(a)
print(b)
print(a.ndim)
#reshape our array
print('***a.shape****')

a.shape = (12,2)
print(a)
print(a.ndim)
print('***d = b.reshape****')
#d =
b.reshape(12,2) #trick: Calculate the factors of 24: 1,2,3,4,6,12,24 
print(b)
#print(d)
#print(d.ndim)
#a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
***a.shape****
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
2
***d = b.reshape****
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


#Shape Vs Reshape

Shape function is either used to get the shape of already existing array by using arry_name.shape method. Another way to use shape is to change array dimensions of the array. But note that shape changes dimensions of the original array



<br>
Reshape also changes the dimension of the array but it generates a new copy of the array in the process. So the original array remains unchanged.

# Concatenation

In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [43]:
print(a)
print(b)


[1 2 3]
[4 5 6]


# hstack

In [45]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

# vstack

In [46]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

# Comparision of Numpy vs List

# Size comparision

In [59]:
import numpy as np
import sys


l_list = range(1000)
#s_list = range(10)
print(l_list)
#print(s_list)
print(sys.getsizeof(1))
print(sys.getsizeof(1)*len(l_list))

print('****numpy***')
a = np.arange(1000)
a.size
print(a.size)
print(a.itemsize)

print(a.itemsize*a.size)

range(0, 1000)
28
28000
****numpy***
1000
4
4000


# Why we need numpy and speed of calculaiton

In [64]:
#Numpy vs List: Speed
import time
def using_List():
    t1 = time.time()#Starting/Initial Time
    
    X = range(10000)
    Y = range(10000)
    
    z = [X[i]+Y[i] for i in range(len(X))]
    
    return time.time()-t1

def using_Numpy():
    t1 = time.time()#Starting/Initial Time
    a = np.arange(10000)
    b = np.arange(10000)
    z =a+b #more convient than a list
    return time.time()-t1


list_time = using_List()
numpy_time = using_Numpy()
print(list_time,numpy_time)
#this line will print an error because Nump somestime can be zero. Run very fast
#print("In this example Numpy is "+str(list_time/numpy_time)+" times faster than a list")


0.003991842269897461 0.0
