# PythonNumpyHands-On

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.
Arbitrary data-types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy arrays are similar to Python lists. The NumPy library provides an array data structure that holds some benefits over Python lists, like–faster access in reading and writing items, is more compact, and is more convenient and efficient.

NumPy is known to provide access to a few substantial tools and techniques that can be utilized to solve mathematical models of problems, that essentially belong to the complexity offered by Science and Engineering. An example, one of these tools is a high-performance multidimensional array object–a powerful data structure, best used to for efficient computation of arrays and matrices. Clearly, to operate and function the best of out these arrays, requires credibility to solve high-level mathematical functions.

NumPy’s main object is the homogeneous multidimensional array.

It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
In NumPy dimensions are called axes. The number of axes is rank.
NumPy’s array class is called ndarray. It is also known by the alias array.

# Create Numpy Array

# 1-Dimensional Array

In [5]:
import numpy as np
#import numpy to make use of it in the program
a = np.array([1,2,3])
print(a)

[1 2 3]


# 2-Dimensional Array

In [6]:
#import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# Intialize Numpy Array

# Initialize all the elements of x X y array to 0

By default you can see below the datatype is float64 that is why it is 0.

In [7]:
#import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#set a datype as integer
np.zeros((3,4),dtype = int)
#eek.zeros(2, dtype = int) 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Arrange the numbers between x and y with an interval of z

In [9]:
#import numpy as np
#the last number 10 is not printed
np.arange(1,10,1)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#import numpy as np
#the last number 10 is not printed
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# Arrange 'z' numbers between x and y

linear Space:
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]

The NumPy linspace function creates sequences of evenly spaced values within a defined interval.

Essentally, you specify a starting point and an ending point of an interval, and then specify the total number of breakpoints you want within that interval (including the start and end points). The np.linspace function will return a sequence of evenly spaced values on that interval.

To illustrate this, here’s a quick example. (We’ll look at more examples later, but this is a quick one just to show you what np.linspace does.)

In [11]:
np.linspace(5,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [13]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

Here the even space is .5

In [14]:
#what is linspace???
#How to use it
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [15]:
#even numbers between 0 to 10
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Filling SAME number in an array of dimension x X y

In [16]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

# Filling RANDOM number in an array of dimension x X y

First note that numpy.random.random is actually an alias for numpy.random.random_sample. I'll use the latter in the following. (See this question and answer for more aliases.)

Both functions generate samples from the uniform distribution on [0, 1). The only difference is in how the arguments are handled. With numpy.random.rand, the length of each dimension of the output array is a separate argument. With numpy.random.random_sample, the shape argument is a single tuple.

For example, to create an array of samples with shape (3, 5), you can write

sample = np.random.rand(3, 5)
or

sample = np.random.random_sample((3, 5))

https://docs.scipy.org/doc/numpy/reference/routines.random.html

In [17]:
np.random.random((2,3))

array([[0.98114331, 0.85746879, 0.36323255],
       [0.26356926, 0.82217992, 0.88892951]])

# Inspecting the array: Checking the size of the array

Shape : Returns a tuple consisting of array Dimensions. 


In [18]:
a = np.array([[2,3,4],[4,4,6]])
print(a.shape)

(2, 3)


In [19]:
s = np.array([[1,2,3,4],[2,3,4,6],[6,7,8,9]])
print(s.shape)

(3, 4)


# Shape: Inspecting the array and  Resize the Array

# SHAPE

Shape function is either used to get the shape of already existing array by using arry_name.shape method.<br>Resize:Another way to use shape is to change array dimensions of the array. But note that shape changes dimensions of the original array



In [20]:
a = np.array([[2,3,4],[4,4,6]])
a.shape = (3,2)
print(a)

[[2 3]
 [4 4]
 [4 6]]


#Trick: x*y = Total number of elements in the array

In [21]:
a = np.array([[2,3,4,4],[2,4,4,6]])
a.shape = (8,1) 
print(a)

[[2]
 [3]
 [4]
 [4]
 [2]
 [4]
 [4]
 [6]]


# ndim:Return the dimension of the array

Make it 1 dimension. 2 dimesion. when we make it 3 dimension it gives and error

# Reshape

Reshape also changes the dimension of the array but it generates a new copy of the array in the process. So the original array remains unchanged.

In [31]:

a = np.arange(24)
print(a)
print(a.ndim)
#reshape our array
b = a.reshape(12,2) #Make it 2 dimensions
print(b)
print(b.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
2


# Shape Vs Reshape

Shape function is either used to get the shape of already existing array by using arry_name.shape method. Another way to use shape is to change array dimensions of the array. But note that shape changes dimensions of the original array



# Reshape

In [19]:
# Python Program illustrating 
# numpy.reshape() method 

import numpy as geek 

array = geek.arange(8) 
print("Original array : \n", array) 

# shape array with 2 rows and 4 columns 
array = geek.arange(8).reshape(2, 4) 
print("\narray reshaped with 2 rows and 4 columns : \n", array) 

# shape array with 2 rows and 4 columns 
array = geek.arange(8).reshape(4 ,2) 
print("\narray reshaped with 2 rows and 4 columns : \n", array) 

# Constructs 3D array 
array = geek.arange(8).reshape(2, 2, 2) 
print("\nOriginal array reshaped to 3D : \n", array) 


Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# Find the number of elements in an array

Returns the count of number of elements in an Array

In [32]:
print(a.size)

24


In [33]:
d = np.array([[1,2,3,4],[4,5,6,4],[6,7,8,9]])
print(d.size)

12


# ndim

nadarray.ndim Dimensions of an Array-

In [34]:
import numpy as np
a= np.arange(24)
print(a.ndim)
b=a.reshape(2,3,4)
print(b.ndim)

1
3


# Find the datatype of the array

In [35]:
a = np.arange(24, dtype=float)
print(a.size)
print(a.dtype)
a

24
float64


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [36]:
b=a.reshape(3,4,2)
b

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

# Numpy Array Mathematics: Addition

In [37]:
import numpy as np
np.sum([10,20])

30

In [38]:
#using a variable that is sum of a+b
a,b = 10,20
np.sum([a,b])

30

In [39]:
np.sum([[1,2],[5,6]],axis = 0)

array([6, 8])

In [24]:
np.sum([[1,2],[5,6]],axis = 1)

array([ 3, 11])

In [25]:
np.sum([[1,2],[5,6]])

14

# Numpy Array Mathematics: Subtraction

In [40]:
np.subtract(10,20)

-10

# All other numpy Mathematics Function

In [41]:
np.multiply(2,3) #Multiplying two numbers

6

In [42]:
np.divide(10,5) #Dividing two numbers

2.0

In [43]:
a =np.array([2,4,6])
b =np.array([1,2,3])
np.multiply(a,b)

array([ 2,  8, 18])

In [44]:
#exp,sqrt,sin,cos,log
print("Exponent : ",np.exp(a))
print("Square root : ", np.sqrt(a))
print("Sin : ", np.sin(a))
print("Cos : ", np.cos(a))
print("Log : ", np.log(a))

Exponent :  [  7.3890561   54.59815003 403.42879349]
Square root :  [1.41421356 2.         2.44948974]
Sin :  [ 0.90929743 -0.7568025  -0.2794155 ]
Cos :  [-0.41614684 -0.65364362  0.96017029]
Log :  [0.69314718 1.38629436 1.79175947]


# Array Comparison

In [45]:
#Element-wise Comparison
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.equal(a,b)

array([False, False,  True])

In [46]:
#Array-wise Comparison
a = [1,2,4]
b = [1,4,4]
c = [1,2,4]
np.array_equal(a,c)

True

# Aggregate Function

In [47]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
print("Sum: ",np.sum(a))
print("Minimum Value: ",np.min(a))
print("Mean: ",np.mean(a))
print("Median: ",np.median(a))
print("Coorelation Coefficient: ",np.corrcoef(a))
print("Standard Deviation: ",np.std(a))

Sum:  7
Minimum Value:  1
Mean:  2.3333333333333335
Median:  2.0
Coorelation Coefficient:  1.0
Standard Deviation:  1.247219128924647


# Concept of Broadcasting

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

Refer to the slide to explain Broad Casting:

Let us first Run this example to undersand Broadcasting. Below the shapes are similar. 

In [50]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a + b 
print (c)

[11 22 33 44]


If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

Broadcasting is possible if the following rules are satisfied −

Array with smaller ndim than the other is prepended with '1' in its shape.

Size in each dimension of the output shape is maximum of the input sizes in that dimension.

An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.

If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

In [34]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([[0,1,2]])
print("First Array: \n",a,'\n')
print("Second Array: \n",b,'\n')
print("First Array + Second Array: \n",a+b,'\n')

First Array: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

Second Array: 
 [[0 1 2]] 

First Array + Second Array: 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]] 



# Indexing and Slicing in Python

In [59]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


extracts only the first row or 0 row

In [61]:
x[0]

array([1, 2, 3])

Extracts Rows up to 1

In [62]:
x[:1]

array([[1, 2, 3]])

Extracts Rows up to 2

In [63]:
x[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
x[:1,1:]

array([[2, 3]])

In [71]:
x[:1,1:]

array([[2, 3]])

Slide 29 : extract  till row 1

In [73]:
x[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
x[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
Slide 30: 

In [75]:
x[1:,]

array([[4, 5, 6],
       [7, 8, 9]])

In [76]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

# SLICING :

Slide 31

In [77]:
x[:2,1:]

array([[2, 3],
       [5, 6]])

In [78]:
x[2]

array([7, 8, 9])

In [79]:
x[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
x[2:,:]

array([[7, 8, 9]])

In [81]:
x[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [82]:
x[1:,:2]

array([[4, 5],
       [7, 8]])

In [83]:
x[1:2,:2]

array([[4, 5]])

In [35]:
a = ['m','o','n','t','y',' ','p','y','t','h','o','n']
a[2:9]

['n', 't', 'y', ' ', 'p', 'y', 't']

In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0]
a[:1]
print(a)
a[:1,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3]])

In [37]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [38]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

# Array Manipulation in Python

# Concatenate

In [86]:
a = np.array([1,2,3])
b= np.array([4,5,6])
#concatenation of two arrays
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Hstack

In [87]:
#Stack array row-wise: Horizontal 
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

# vstack

In [88]:
#Stack array row-wise: Vertically
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
#Combining Column-wise
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Splitting Array

# hsplit

numpy.hsplit(ary, indices_or_sections)

In [6]:
import numpy as np

In [8]:
x = np.arange(16).reshape(4,4)
print(x,"\n\n")
print(np.hsplit(x,2))
print("\n\n", np.hsplit(x,np.array([2,3])))

print("\n\n", np.hsplit(x,np.array([2,5])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


# Advantages of Numpy Over a List

Why Python List consumes more space than NUMPY

The difference is mostly due to "indirectness" -- a Python list is an array of pointers to Python objects, at least 4 bytes per pointer plus 16 bytes for even the smallest Python object (4 for type pointer, 4 for reference count, 4 for value -- and the memory allocators rounds up to 16). A NumPy array is an array of uniform values -- single-precision numbers takes 4 bytes each, double-precision ones, 8 bytes. Less flexible, but you pay substantially for the flexibility of standard Python lists!

In [44]:
#Numpy vs List: Memory size
import numpy as np
import sys

#define a list
l = range(1000)
print("Size of a list: ",sys.getsizeof(1)*len(l))

#define a numpy array
a = np.arange(1000)
print("Size of an np array: ",a.size*a.itemsize)

Size of a list:  28000
Size of an np array:  4000


In [49]:
#Numpy vs List: Speed
import time
def using_List():
    t1 = time.time()#Starting/Initial Time
    X = range(10000)
    Y = range(10000)
    z = [X[i]+Y[i] for i in range(len(X))]
    return time.time()-t1

def using_Numpy():
    t1 = time.time()#Starting/Initial Time
    a = np.arange(10000)
    b = np.arange(10000)
    z =a+b #more convient than a list
    return time.time()-t1
list_time = using_List()
numpy_time = using_Numpy()
print(list_time,numpy_time)
#this line will print an error because Nump somestime can be zero. Run very fast
#print("In this example Numpy is "+str(list_time/numpy_time)+" times faster than a list")

0.003998994827270508 0.0
