# Python-SciPy Library

Import Data

In [1]:
import pandas as pd
#importing data
data = pd.read_excel('somecars1.xlsx')
#print the dataset
data
print(data)

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
6   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
7   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
8   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
9   17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
10  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
11  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
12  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
13  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
14  10.4  

# scipy.cluster

To divide a dataset into k clusters. 

In [6]:
#import libraries
import pandas  as pd
from  scipy.cluster.vq import kmeans, vq
#importing data
data = pd.read_excel('somecars1.xlsx') 
#find out centroids with the help of kmeans functions
#k, number of clusters required
centroid, _ = kmeans(data,3)
#_ It's just a variable name, and it's conventional in python to use _ for throwaway variables. 
#It just indicates that _ isn't actually used.

#find out the cluster index for each record with vector quantization function
#vq(data,centroid)
idx, _ = vq(data,centroid)
#print the cluster index array
idx
#below there are 3 clusters (0,1,2)
#centroid, _ = kmeans(data,3) we can change the value of 3 to 2
#print (data)

array([0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1, 0, 0, 0, 2, 2, 1,
       1, 0, 0, 1, 0, 1, 0])

In [3]:
#also print the centroids for each of the 11 columns and there are K=3 values. 
centroid

array([[1.46444444e+01, 8.00000000e+00, 3.88222222e+02, 2.32111111e+02,
        3.34333333e+00, 4.16155556e+00, 1.64044444e+01, 0.00000000e+00,
        2.22222222e-01, 3.44444444e+00, 4.00000000e+00],
       [1.68333333e+01, 7.66666667e+00, 2.84566667e+02, 1.58333333e+02,
        3.03333333e+00, 3.62500000e+00, 1.77683333e+01, 1.66666667e-01,
        0.00000000e+00, 3.00000000e+00, 2.33333333e+00],
       [2.37357143e+01, 4.71428571e+00, 1.28500000e+02, 1.01285714e+02,
        3.99142857e+00, 2.58235714e+00, 1.84514286e+01, 7.14285714e-01,
        6.42857143e-01, 4.14285714e+00, 2.64285714e+00]])

Now perform data whitening

In [7]:
#import libraries
import pandas  as pd
from  scipy.cluster.vq import kmeans, vq, whiten 
#importing data
data = pd.read_excel('somecars1.xlsx') 
#whiten data
data = whiten(data)
print(data)
#find out centroids with the help of kmeans functions
#k, number of clusters required
centroid, _ = kmeans(data,3)
#find out the cluster index for each record with vector quantization function
#vq(data,centroid)
idx, _ = vq(data,centroid)
#print the cluster index array
idx

[[ 3.75298379  3.43361612  1.31900894  1.64580862  7.57136329  2.72567145
   9.40878577  0.          2.06094026  5.35068101  2.57460122]
 [ 3.75298379  3.43361612  1.31900894  1.64580862  7.57136329  2.99095627
   9.72889026  0.          2.06094026  5.35068101  2.57460122]
 [ 4.07466812  2.28907741  0.89033103  1.39145638  7.47429453  2.41357167
  10.63775839  2.06094026  2.06094026  5.35068101  0.6436503 ]
 [ 3.8244692   3.43361612  2.12690191  1.64580862  5.97943563  3.34466936
  11.11219898  2.06094026  0.          4.01301075  0.6436503 ]
 [ 3.34194271  4.57815482  2.9677701   2.6183319   6.11533189  3.5787442
   9.72889026  0.          0.          4.01301075  1.28730061]
 [ 2.55560325  4.57815482  2.9677701   3.66566466  6.2318144   3.71398744
   9.05438436  0.          0.          4.01301075  2.57460122]
 [ 4.36060974  2.28907741  1.20936632  0.92763759  7.1636745   3.31866104
  11.43230348  2.06094026  0.          5.35068101  1.28730061]
 [ 4.07466812  2.28907741  1.16072786  1.4

array([1, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0,
       0, 1, 2, 1, 1, 1, 2])

In [ ]:
#also print the centroids
centroid

# scipy.stats

find the mean and standard deviation

In [ ]:
#import numpy
import numpy as np 
#create the marks array 
coffee = np.array([15,18,20,26,32,38,32,24,21,16,13,11,14])
print(coffee.mean(), coffee.std())
#let us see the data distribution by plotting it
import matplotlib.pyplot as pyplot
plt.plot(range(13),coffee)

Find the z-score

In [ ]:
#import numpy
import numpy as np 
#create the marks array 
coffee = np.array([15,18,20,26,32,38,32,24,21,16,13,11,14])
from scipy import stats
#find the zscore
print(stats.zscore(coffee))
print(coffee.mean(), coffee.std())
#let us see the data distribution by plotting it
import matplotlib.pyplot as pyplot
plt.plot(range(13),coffee)

In [ ]:
#import numpy
import numpy as np 
#create the marks array 
coffee = np.array([15,18,20,26,32,38,32,24,21,16,13,11])
#import scipy stats
from scipy import stats
#find the zscore
print(coffee.mean(), coffee.std())
#let us see the data distribution by plotting it
import matplotlib.pyplot as pyplot
plt.plot(range(12),coffee)

In [5]:
#import numpy
import numpy as np
from scipy import stats
#create the numpy array consisting of frequency of people going to gym and frequency of smoking  
obs = np.array([[7,1,3],[87,18,84],[12,3,4],[9,1,7]])
#since we are lookingfor only p values, ignore the rest
_,p,_,_ = stats.chi2_contingency(obs)
#print p
p

0.48284216946545633

# scipy.optimize 

In [ ]:
#generate one function and plot with matplotlib
#import matplotlib
import matplotlib.pyplot as plt
#import numpy
import numpy as np
x= np.arange(0.0,1.0,0.1)
#create function
def f(x):
    return -np.exp(-(x-0.7)**2)
#plot function
plt.plot(x,f(x),'o-')
plt.grid()

In [ ]:
#find at which x value we get the minimum function
from scipy import optimize
#generating the function
import numpy as np
def f(x):
    return -np.exp(-(x-0.7)**2)
#find the minimum of the function
result = optimize.minimize_scalar(f)
#now find the corresponding x value
x_min = result.x
#print the x value
x_min

# scipy.integrate 

In [ ]:
#import scipy integrate
import scipy.integrate as intg
#create one function to find the integration
def integrad(x):
    return x**2
#apply quad() function, get only the answer, ignore rest
ans,_ = intg.quad(integrad,0,1)
#print ans
ans

# scipy.linalg

Determinant of a square matrix

In [ ]:
#import scipy linalg package
from scipy import linalg
#import numpy to the square matrix
import numpy as np
data = np.array([[1,2,3],[3,4,5],[5,6,7]])
#find determinant 
linalg.det(data)

Inverse of a square matrix

In [ ]:
#import scipy linalg package
from scipy import linalg
#import numpy to the square matrix
import numpy as np
data = np.array([[1,2,3],[3,4,5],[5,6,7]])
#find determinant 
linalg.inv(data)

Eigen values of a square matrix

In [ ]:
#import scipy linalg package
from scipy import linalg
#import numpy to the square matrix
import numpy as np
data = np.array([[1,2,3],[3,4,5],[5,6,7]])
#find determinant 
linalg.eigvals(data)

# scipy.fftpack

Create one noisy signal

In [ ]:
#craete noisy signal
import matplotlib.pyplot as plt
import numpy as np
#create a signal with time_step=0.02
time_step = 0.02
period = 5
time_vec= np.arange(0,20, time_step)
sig = np.sin(2*np.pi/period*time_vec)+ 0.5*np.random.randn(time_vec.size)
plt.plot(time_vec,sig)
plt.show()

Apply fft

In [ ]:
from scipy import fftpack
#Since we didnt not know the signal frequency, we only knew the sampling time step of the signal sig.
#The function fftfreq() returns the FFT sample frequency points.
sample_freq = fftpack.fftfreq(sig.size, d = time_step)
#now apply the fft() in the signal to find the discrete fourier transform
sig_fft = fftpack.fft(sig)
#Calculate the absolute value element-wise
power = np.abs(sig_fft)
plt.figure(figsize=(20,5))
#plot the absolute values of each sample_freq
plt.plot(sample_freq, power)
plt.show()
#here at sample_freq = 0.2 and -0.2 we have absolute values of 5.15943859e+02 = 515.9438593147901 
#print(sample_freq)
#print(power)

Apply inverse fft to get the filtered signal

In [ ]:
#Filter out the sample frequencies that are greater than 0 with numpy.where(condition) 
pos_mask = np.where(sample_freq > 0)
#Apply the fiter on smaple_freq and store the +ve sample_freq on freqs 
freqs = sample_freq[pos_mask]

#print(power[pos_mask].argmax())
#Find the peak frequency, here we focus on only the positive frequencies
peak_freq = freqs[power[pos_mask].argmax()]
#now get an array copy of the signal where we already applied fft.
high_freq_fft = sig_fft.copy()
#assign the ones greater than peak freq as 0 in order to remove the noise
high_freq_fft[np.abs(sample_freq) > peak_freq] = 0

#print(high_freq_fft)
#Now apply inverese fft on the new high_freq_fft this will be the filtered signal
filtered_sig = fftpack.ifft(high_freq_fft)
#plot 
plt.figure(figsize=(6, 5))
#now plot the original signal for reference
plt.plot(time_vec, sig, label='Original signal')
#now plot the filtered signal
plt.plot(time_vec, filtered_sig, linewidth=3, label='Filtered signal')
#add label, legend
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.legend(loc='best')
#show
plt.show()

# scipy.signal

Resampling

In [ ]:
#scipy.signal uses FFT to resample a 1D signal.
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
#Now let us create a signal with 200 data point
t = np.linspace(-10, 10, 200) #Defining Time Interval
y = np.sin(t)                         
x_resampled=signal.resample(y, 100) #Number of required samples is 100
plt.plot(t, y)
#for x axis slice t into 2 step size
plt.plot(t[::2], x_resampled, 'o') 
plt.show()

In [ ]:
import numpy as np
t = np.linspace(-10, 10, 200)
x = np.sin(t)
from scipy import signal
x_resampled = signal.resample(x, 25) # Number of required samples is 25
plt.plot(t, x) 
plt.plot(t[::8], x_resampled, 'o')
plt.show()