# 1. Numpy Arrray of 5x5 dimension with all elements as 0

In [3]:
import numpy as np
# numpy full() function fills all value to zero
a = np.full((5,5),0)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 2. Numpy Array with initial value 10 and final value 100 with interval 5

In [5]:
import numpy as np
# numpy arange(initial, final, interval), where final is exclusive
b = np.arange(10,101,5)
b

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

# 3. 2-D numpy array
   i. Find the number of elements      ii. Find the datatype of array 

In [20]:
import numpy as np
# Assigning a 2-D numpy array
c1 = np.array([[10,20,30,40,50,60]])
# Using reshape to have the required dimension 2x3
c2 = c1.reshape(2,3)
print(c2)
print("Number of elements in the array:",c2.size)
print("Datatype of elements in the array:",c2.dtype)

[[10 20 30]
 [40 50 60]]
Number of elements in the array: 6
Datatype of elements in the array: int32


# 4. Perform arithmetic operations (+,-,*,/) on numpy array

In [25]:
import numpy as np

first = np.array([1,2,3])
second = np.array([4,5,6])

add =np.add(first,second)
print("Addition:",add)

subtract=np.subtract(first,second)
print("Subtraction:",subtract)

mul = np.multiply(first,second)
print("Multiplication:",mul)

div =np.divide(first,second)
print("Division:",div)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [ ]:
5. 

In [37]:
import numpy as np
# Using linspace to set values of numpy array 10-90
# As we have to set dimension to 3x3 let us take 9 elements in array
arr = np.linspace(10,90,9)
# Reshape to the required dimension 3x3
arr1=arr.reshape(3,3)
print(arr1)

# Third column of numpy array
print("\nThird column :")
print(arr1[:,2])

# Second row of the numpy array
print("\nSecond row :")
print(arr1[1,:])

# Intersection of first two rows and first two columns of the numpy array
print("\nIntersection :")
print(arr1[:2,:2])

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]

Third column :
[30. 60. 90.]

Second row :
[40. 50. 60.]

Intersection :
[[10. 20.]
 [40. 50.]]
