In [120]:
class BankAccount:
    balance=0
    def check_balance(self):
        print("The current balance is: ",self.balance)
    def deposit(self, depositAmount):
        self.check_balance()
        self.balance=self.balance+depositAmount
    def withdraw(self, withdrawAmount):
        if withdrawAmount>self.balance:
            print("Insufficient Amount")
        else:
            self.balance=self.balance-withdrawAmount             

In [121]:
ob1=BankAccount()

In [122]:
ob1.check_balance()

The current balance is:  0


In [123]:
ob1.deposit(2000)

The current balance is:  0


In [112]:
ob1.check_balance()

The current balance is:  2000


In [113]:
ob1.withdraw(500)

In [114]:
ob1.check_balance()

The current balance is:  1500


In [115]:
ob1.withdraw(3000)

Insufficient Amount


In [131]:
class MinimumBalanceAccount(BankAccount):
    min_bal=5000
    def withdraw(self, withdrawAmount):
        if withdrawAmount>self.min_bal:
            print("You cannot withdraw:", withdrawAmount)
            print("The minimum balance is",self.min_bal)
        else:
            newAmount=self.min_bal-withdrawAmount
            return newAmount
            

In [127]:
        def withdraw(self, withdrawAmount):
            if withdrawAmount>self.min_bal:
                print("You cannot withdraw:", withdrawAmount)
                print("the minimun balance is:",self.min_bal)
            else:
                self.min_bal=self.min_bal-withdrawAmount  

In [ ]:
class MinimumBalanceAccount(BankAccount):
    min_bal=5000
    def withdraw(self, withdrawAmount):
        if withdrawAmount>self.min_bal:
                print("You cannot withdraw:", withdrawAmount)
                print("the minimun balance is:",self.min_bal)
        else:
                self.min_bal=self.min_bal-withdrawAmount 
            
        
             
        

In [132]:
ob2=MinimumBalanceAccount()

In [133]:
ob2.withdraw(1000)

4000

In [134]:
import numpy as np

In [154]:
a=np.zeros((5,5), dtype=int)

In [155]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [156]:
np.full((5,5),0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [159]:
q=np.arange(10, 105,5)

In [161]:
print(q)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [164]:
w=np.array([10,20,30,40,50,60]).reshape(2,3)

In [165]:
w

array([[10, 20, 30],
       [40, 50, 60]])

In [182]:
print(w)

[[10 20 30]
 [40 50 60]]


In [183]:
w.dtype

dtype('int32')

In [184]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])

In [186]:
n1+n2

array([5, 7, 9])

In [187]:
np.add(n1,n2)

array([5, 7, 9])

In [188]:
np.subtract(n1,n2)

array([-3, -3, -3])

In [189]:
np.multiply(n1,n2)

array([ 4, 10, 18])

In [190]:
np.divide(n1,n2)

array([0.25, 0.4 , 0.5 ])

In [193]:
n1/n2

array([0.25, 0.4 , 0.5 ])

In [224]:
s=np.arange(10,91,10).reshape(3,3)

In [195]:
s

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [208]:
p=s[:,[2]]

In [209]:
np.ndim(p)

2

In [213]:
y=s[[1],:]

In [214]:
np.ndim(y)

2

In [215]:
s[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [216]:
s[0:1,0:1]

50