In [1]:
import numpy as np

In [6]:
'''
1.
    Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a numpy array of the 
    given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
    [
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]
    ]
'''

def solve(dimesions, value):
    return np.full(dimesions, value)

In [7]:
solve((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [25]:
'''
2. Create a method that takes n numpy arrays of same dimensions sums them and return the answer
'''
def sum_coeff(arrays):
    result = np.zeros(len(arrays[0]))
    for arr in arrays:
        result += arr
    return result

In [26]:
sum_coeff([np.array([1, 2, 3]), np.array([1, 2, 6]), np.array([6, 2, 1])])

array([ 8.,  6., 10.])

In [37]:
'''
3. Given a 2 D Array of N X M Dimesion, Write a function that accepts this array as well as two numbers N and M
   The method should return the top-left N X M sub matrix e.g:
   [
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
   ]
   
   sub_matrix(matrix, 2, 2) -> should return :
   [
       [1, 2]
       [4, 5]
   ]
'''

def top_left_sub_matrix(matrix, n, m):
    return matrix[:n, :m]

In [38]:
matrix = np.array([
   [1, 2, 3],
   [4, 5, 6],
   [7, 8, 9],
])
top_left_sub_matrix(matrix, 2, 2)

array([[1, 2],
       [4, 5]])

In [39]:
'''
4. Given a 2 D Array of N X M Dimesion, Write a function that accepts this array as well as two numbers N and M
   The method should return the bottom-right N X M sub matrix e.g:
   [
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
   ]
   
   sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
   [
       [5, 6]
       [8, 9]
   ]
'''
def bottom_right_sub_matrix(matrix, n, m):
    return matrix[n:, m:]

In [41]:
matrix = np.array([
   [1, 2, 3],
   [4, 5, 6],
   [7, 8, 9],
])
bottom_right_sub_matrix(matrix, 1, 1)

array([[5, 6],
       [8, 9]])

In [46]:
'''
5. Given a 1 D Numpy Array  Write a function that accepts this array as parameters.
   The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:
    [1, 1, 1]
   solution(arr) -> should return :
   {'mean': 1.0, 'std_dev': 0.0}
'''
def solution(arr):
    return { 'mean': arr.mean(), 'std_dev': arr.std() }

In [47]:
solution(np.array([1, 1, 1]))

{'mean': 1.0, 'std_dev': 0.0}